Health-Education-England/tis-trainee-forms

.github/workflows/analyze-with-sonarqube.yml
Add github actions pipeline configuration file with steps to build the
project and analyse with sonarcloud.
TISNEW-3946
=> chore: Add GitHub Actions analysis pipeline

build.gradle
=> chore: Add Spring Boot Actuator health endpoint

.github/workflows/ci-cd-workflow.yml
=> chore: Update AWS cluster name

src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartAResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/util/HeaderUtil.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/TestUtil.java
=> style: Resolve CheckStyle violations

src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartBDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/WorkDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/Work.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartBResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBServiceImplTest.java
=> Feat/formR PartB Section2

src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartBDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/FormRPartB.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartBResourceTest.java
- Add compliments field
- Update unit tests
TISNEW-4558
=> feat: Add field for formR part b section 6

src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartAResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartBResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartADto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartASimpleDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartBDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartSimpleDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/enumeration/LifecycleState.java, src/main/java/uk/nhs/hee/tis/trainee/forms/mapper/FormRPartAMapper.java, src/main/java/uk/nhs/hee/tis/trainee/forms/mapper/FormRPartBMapper.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/FormRPartB.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/FormRPartARepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/FormRPartBRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAService.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBService.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/impl/FormRPartAServiceImpl.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/impl/FormRPartBServiceImpl.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartAResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartBResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAServiceImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBServiceImplTest.java
1. add lifecycleState field in formRPart A & B
2. refactor GET FormRPart endpoints
3. add PUT FormRPart endpoints
4. unit tests
Please do NOT merge until the trainee-ui PR is raised.
=> Feat/lifecycleState formR parts

src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartBResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartBValidator.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/FormRPartBRepository.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartBResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartAValidatorTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartBValidatorTest.java
Pretty much the same as FormRPartA. Added unique validation for FormR PartB draft.
=> feat: add Draft Unique validation for FormR PartB

src/main/java/uk/nhs/hee/tis/trainee/forms/dto/CovidDeclarationDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/CovidDeclaration.java
=> feat: add fields for Covid section3&4

src/main/java/uk/nhs/hee/tis/trainee/forms/model/AbstractForm.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/FormRPartA.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/FormRPartB.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/AbstractCloudRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/FormRPartARepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/FormRPartBRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/S3FormRPartARepositoryImpl.java
This change should fix duplication code smell and make more testable.
TISNEW-5376: Show unsubmitted forms
=> refactor: define an abstract form and cloud repository

.github/workflows/ci-cd-workflow.yml
soz... it's hard to pick this up on github diffs
=> fix: add environment to name of "Deploy" jobs and fix indents

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartAResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/mapper/FormRPartBMapper.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/AbstractCloudRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/exception/ExceptionTranslator.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FormSwitchResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/repository/S3FormRPartARepositoryImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/repository/S3FormRPartBRepositoryImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAServiceImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBServiceImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormSwitchServiceImplTest.java
=> refactor: Fix code smells

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/forms/api/FeatureFlagResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/config/FeatureConfigurationProperties.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FeatureFlagResourceTest.java
Create a feature flag for the covid declaration as a replacement for the
form switch functionality.
TIS21-1452
=> feat: Add COVID feature flag

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartBDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/FormRPartB.java, src/test/resources/forms/testFormRPartB.json
add reference to account for the new 'other' selection in FormRPartB and update tests
TIS21-1659
=> Add prevRevalBodyOther to form r part b

.github/workflows/ci-cd-workflow.yml, .github/workflows/pr-analysis.yml, README.md
=> chore: Rename master to main

src/main/java/uk/nhs/hee/tis/trainee/forms/migration/DeleteTestForm.java, src/test/java/uk/nhs/hee/tis/trainee/forms/migration/DeleteTestFormTest.java
Form was submitted by dev team to validate user data.
NO-CARD: Support query tracked in spreadsheet
=> chore(support): delete test FormR PartB

src/main/java/uk/nhs/hee/tis/trainee/forms/migration/DeleteTestForm.java, src/test/java/uk/nhs/hee/tis/trainee/forms/migration/DeleteTestFormTest.java
NO-CARD: Support queries tracked in spreadsheet
=> chore(doc): Add Javadoc to changeunit

src/main/java/uk/nhs/hee/tis/trainee/forms/migration/SortWorkPlacements.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/forms/migration/SortWorkPlacementsTest.java
=> Fix: sort work placements

src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartADto.java
=> fix: change type to LocalDate from localDateTime

src/main/java/uk/nhs/hee/tis/trainee/forms/repository/FormRPartARepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/FormRPartBRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/impl/FormRPartAServiceImpl.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/impl/FormRPartBServiceImpl.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAServiceImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBServiceImplTest.java
=> fix: use UUID instead of String for ID lookup

.aws/task-definition-template.json, README.md, build.gradle, src/main/java/uk/nhs/hee/tis/trainee/forms/TraineeFormsApplication.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/FeatureFlagResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartAResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartBResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/config/AwsXrayConfiguration.java, src/main/java/uk/nhs/hee/tis/trainee/forms/config/AwsXrayInterceptor.java, src/main/java/uk/nhs/hee/tis/trainee/forms/event/FormDeleteEventListener.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/impl/FormRPartAServiceImpl.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/impl/FormRPartBServiceImpl.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/forms/config/AwsXrayConfigurationTest.java
=> feat: add xray tracing to application

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/forms/config/ApplicationConfiguration.java, src/main/java/uk/nhs/hee/tis/trainee/forms/config/AwsXrayInterceptor.java, src/main/java/uk/nhs/hee/tis/trainee/forms/config/EcsMetadataConfiguration.java, src/main/java/uk/nhs/hee/tis/trainee/forms/config/SentryConfiguration.java, src/test/java/uk/nhs/hee/tis/trainee/forms/config/ApplicationConfigurationTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/config/AwsXrayInterceptorTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/config/EcsMetadataConfigurationTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/config/SentryConfigurationTest.java
=> feat: log ECS metadata with X-Ray and Sentry

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/forms/config/Config.java
configure project so all unknown properties are false by default
TIS21-4379
=> fix: unknown field exception

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/WorkDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/Work.java, src/test/java/uk/nhs/hee/tis/trainee/forms/repository/S3FormRPartBRepositoryImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBServiceTest.java, src/test/resources/forms/testFormRPartB.json
=> feat: add siteKnownAs field in Form R Part B Type of Work

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/api/FeatureFlagResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartBResource.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FeatureFlagResourceTest.java
=> Disable covid declaration feature flag

README.md, build.gradle.kts, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FeatureFlagResourceTest.java
until the logic for the FE around unsubmitted/draft forms is agreed
TIS21-5401
=> feat: temp re-enable covid declaration flag

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartAValidator.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartAValidatorTest.java
Due to occasional missing value in submitted DTO, which requires a proper fix.
TIS21-5599
=> fix: set default WTE

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/annotations/LegalAgeValidator.java, src/main/java/uk/nhs/hee/tis/trainee/forms/annotations/MaxDateValidator.java, src/main/java/uk/nhs/hee/tis/trainee/forms/annotations/MinDateValidator.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartADto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartBDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/WorkDto.java, src/test/java/uk/nhs/hee/tis/trainee/forms/annotations/LegalAgeValidatorTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormFieldValidationServicePartATest.java
Also general fixes to better handle nulls in date annotations; prohibiting nulls is better handled with an explicit separate @NotNull annotation.
NO-TICKET
=> fix: allow completion date to be null

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/config/Config.java, src/main/java/uk/nhs/hee/tis/trainee/forms/config/StringDeserializer.java, src/test/java/uk/nhs/hee/tis/trainee/forms/config/ConfigTest.java
=> feat: trim all form strings

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartBValidator.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartBDto.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartBValidatorTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormFieldValidationServicePartBTest.java
As per
https://hee-nhs-tis.slack.com/archives/G0135LS4JVA/p1718104244591819
NO-TICKET
=> fix: relax currentRevalDate validation

build.gradle.kts, src/main/resources/templates/conditions-of-joining/gg10.html, src/main/resources/templates/conditions-of-joining/gg9.html, src/test/java/uk/nhs/hee/tis/trainee/forms/api/ConditionsOfJoiningResourceTest.java
TIS21-6106
TIS21-6122
TIS21-6123
=> fix: make COJ PDF checkboxes readonly 

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartAResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartBResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartBValidator.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/FormFieldValidationService.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAService.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartBValidatorTest.java
Include trainee id where omitted.
Make FormRPart[X] consistent term.
NO-TICKET
=> chore: improve form logging

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/LtftResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/enumeration/LifecycleState.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/LtftFormRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
API gateway changes: https://github.com/Health-Education-England/TIS-OPS/pull/929
TIS21-7039
=> feat: delete LTFT endpoint

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResource.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceTest.java
Create an admin unsubmit endpoint
`/api/forms/admin/ltft/{formId}/unsubmit`.
TIS21-6705
TIS21-7007
=> feat(ltft): admin unsubmit endpoint

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/enumeration/LifecycleState.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
=> feat: increment revision on unsubmit

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/mapper/LtftMapper.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/AbstractAuditedForm.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/Person.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/content/LtftContent.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
Add an endpoint `PUT: /api/admin/ltft/{formId}/assign` to allow an admin to be assigned to the application.
Update the assigned admin and return the updated form.
TIS21-6636
TIS21-7151
=> feat(ltft): assign admin endpoint

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/LtftSummaryDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/mapper/LtftMapper.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
fix: add status details (reason & message) and modifiedByRole to LtftSummaryDto
TIS21-6706
TIS21-7161
fix: add formRef to LtftSummaryDto
TIS21-7080
TIS21-7109
=> fix: add status details and modifiedByRole to DTO

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/main/resources/application-local.yml, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
Note that this will require changes in tis-trainee-notifications and informing the NDW of the new structure.
TIS21-7182
=> fix: export LTFT DTO

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/interceptor/AdminIdentityInterceptor.java, src/test/java/uk/nhs/hee/tis/trainee/forms/interceptor/AdminIdentityInterceptorTest.java
I was a bit confused by the request path :/
TIS21-7304
=> fix: API path for admin/ltft

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/LtftResource.java, src/main/resources/templates/ltft/trainee.html, src/test/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
Sample PDF:
[ltft_23c306eb-f644-4dfa-8098-12f956d6873b.pdf](https://github.com/user-attachments/files/20840357/ltft_23c306eb-f644-4dfa-8098-12f956d6873b.pdf)
TIS21-7324
TIS21-7398
=> feat: LTFT PDF for trainee

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceIntegrationTest.java, src/main/resources/templates/ltft/trainee.html
=> fix: LTFT rejected PDF

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/model/AbstractFormR.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/FormRPartA.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/FormRPartB.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/AbstractCloudRepository.java, src/test/java/uk/nhs/hee/tis/trainee/forms/repository/S3FormRPartARepositoryImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/repository/S3FormRPartBRepositoryImplTest.java
=> fix: populate programme membership ID in FormR

.github/CODEOWNERS, build.gradle.kts
refactor the codowners to be consistent and ensure all files are covered with a default to catch new files
TIS21-7826
=> refactor: update CODEOWNERS
