.aws/task-definition.json
The task definition's default image tag should point to a valid image.
TISNEW-3848
=> chore: Change default image tag to a valid tag

src/main/resources/application.yml
AWS ALB is unable to rewrite paths, so to avoid a separate nginx
instance the service must have its own context path.
TISNEW-3848
=> refactor: Set context path

.aws/task-definition.json
The DB_NAME secret does not exist and is not required at this time,
remove it from the task definition file.
TISNEW-3848
=> chore: Remove DB_NAME secret from task definition

src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartAResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartAValidator.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/FormRPartARepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/exception/ErrorConstants.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/exception/ErrorVM.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/exception/ExceptionTranslator.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/exception/FieldErrorVM.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartAResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartAValidatorTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/exception/ExceptionTranslatorTest.java
1. add Controller Advice to forms service to deal with the Exception Response which is referenced from the tcs service.
2. add FormR PartA validator and add validation for checking if the draft is unique for both update and creation APIs.
3. add unit tests for the newly added validator.
When the validation failes, it returns 400 Bad Request http status and the format of reponse body is below:
```
{
"message": "error.validation",
"description": null,
"fieldErrors": [
{
"objectName": "FormRPartADto",
"field": "lifecycleState",
"message": "Draft form R Part A already exists"
}
]
}
```
=> feat: add Draft Unique validation for FormR PartA

src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartAResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartBResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/util/AuthTokenUtil.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/FormRPartARepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/FormRPartBRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAService.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBService.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/impl/FormRPartAServiceImpl.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/impl/FormRPartBServiceImpl.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartAResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartBResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/util/AuthTokenUtilTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAServiceImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBServiceImplTest.java
Currently the trainee ID is provided as part of the request, but this
would potentially allow users to access data that is not theirs. Instead
the authentication token should be used to retrieve the logged in user's
TIS ID directly.
TISNEW-3833
=> feat: Use the trainee's TIS ID from token

.aws/task-definition-pre-prod.json, .aws/task-definition-prod.json
Both preprod and prod currently use the same task role, which only has
permissions to the preprod bucket. As a result the forms functionality
does not work in the prod environment.
Use seperate task roles for both preprod and prod.
TIS21-1457
=> chore: Use correct permissions depending on env

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/forms/migration/RecalculateTotalLeave.java, src/test/java/uk/nhs/hee/tis/trainee/forms/migration/RecalculateTotalLeaveTest.java
The `totalLeave` field was not correctly populated for some forms,
create a migrator to recalculate the field any record where it is zero.
TIS21-2791
=> fix: recalculate total leave on all FormR Part Bs

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartBDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/FormRPartB.java, src/test/java/uk/nhs/hee/tis/trainee/forms/repository/S3FormRPartBRepositoryImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBServiceImplTest.java, src/test/resources/forms/testFormRPartB.json
…vedDeclarations` to `FormRPartBDto` and `FormRPartB`
TIS21-2965: FormR Part B: Resolved declaration required if previous unresolved declaration given
=> fix: add "haveCurrentUnresolvedDeclarations" and "havePreviousUnresolvedDeclarations" to FormRPartBDto and FormRPartB

src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartADto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartBDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartSimpleDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/AbstractForm.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/AbstractCloudRepository.java, src/test/java/uk/nhs/hee/tis/trainee/forms/repository/S3FormRPartARepositoryImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/repository/S3FormRPartBRepositoryImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAServiceImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBServiceImplTest.java, src/test/resources/forms/testFormRPartA.json, src/test/resources/forms/testFormRPartB.json
change type of submission date to 'LocalDateTime' to add hours and minutes with the date when saving a new form. 
previous forms are in a LocalDate format and need to be converted to LocalDateTime using .atStartOfDay() to populate the time
This PR is dependant on PR 'Sort form Rs by date time and display time for submitted forms' in trainee-ui and will need to be merged together
TIS21-3088
=> Sort form Rs by date time and display time for submitted forms

src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartADto.java
this is a hotfix for Sort form 'Rs by date time and display time for submitted forms #357' for ticket TIS21-3088
the startDate when changed to LocalDateTime was preventing the forms from being saved, this does not need to be in this format and can remain a LocalDate type
=> refactor: change startDate type to LocalDate from LocalDateTime

src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartADto.java
Reverts Health-Education-England/tis-trainee-forms#361
this must be reverted first followed by both PRs 'Revert "Sort form Rs by date time and display time for submitted forms"' and 'Revert "Sort form Rs by date time and display time for submitted forms"' in trainee-ui and trainee-forms together to get stage back to its previous state. 
this is due to the current version affecting the admins-ui not being able to open form-Rs due to the changes in the forms date types being unable to be parsed, this is also affecting trainee-ui when trying to open the older formRs
=> Revert "refactor: change startDate type to LocalDate from LocalDateTime"

src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartADto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartBDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartSimpleDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/AbstractForm.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/AbstractCloudRepository.java, src/test/java/uk/nhs/hee/tis/trainee/forms/repository/S3FormRPartARepositoryImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/repository/S3FormRPartBRepositoryImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAServiceImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBServiceImplTest.java, src/test/resources/forms/testFormRPartA.json, src/test/resources/forms/testFormRPartB.json
Reverts Health-Education-England/tis-trainee-forms#357
this must be reverted allong with  'Revert "Sort form Rs by date time and display time for submitted forms"' in trainee-ui after Revert "refactor: change startDate type to LocalDate from LocalDateTime" in trainee forms
this is due to the current version affecting the admins-ui not being able to open form-Rs due to the changes in the forms date types being unable to be parsed, this is also affecting trainee-ui when trying to open the older formRs
=> Revert "Sort form Rs by date time and display time for submitted forms"

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/forms/model/AbstractFormMongoEventListener.java, src/test/java/uk/nhs/hee/tis/trainee/forms/model/AbstractFormMongoEventListenerTest.java
The form ID number is a different format depending on whether the form The form ID number is a different format depending on whether the form was ever saved as a draft or not, direct submission results in a UUID style ID e.g. c95f2312-a08c-46d4-8e0c-5c13215c96d0 but if the form was saved as a draft before later submitting the ID will be in the ObjectId style e.g. 63a3376e7199d510f8f56808
Use an event listener to populate the form ID with a UUID string representation before converting it to a document, this avoids Mongo from setting the ObjectId automatically.
A follow up submission will migrate the existing ObjectIds to the new standardised UUID string format.
TIS21-4006
[TIS21-4006]: https://hee-tis.atlassian.net/browse/TIS21-4006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
=> fix: create consistent form ids

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/forms/migration/ConvertObjectIdsToUuidStrings.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/forms/migration/ConvertObjectIdsToUuidStringsTest.java
All new forms are created with UUID strings as the ID, but legacy forms which went through the draft lifecycle state were created with an ObjectId instead of UUID.
Create a migrator to find all ObjectId based forms and convert them to use a UUID string based ID.
TIS21-4006
TIS21-4026
[TIS21-4006]: https://hee-tis.atlassian.net/browse/TIS21-4006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TIS21-4026]: https://hee-tis.atlassian.net/browse/TIS21-4026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: convert ObjectIds to UUID strings

src/main/java/uk/nhs/hee/tis/trainee/forms/migration/ConvertObjectIdsToUuidStrings.java, src/test/java/uk/nhs/hee/tis/trainee/forms/migration/ConvertObjectIdsToUuidStringsTest.java
DocumentDB does not support filtering on a field type, retrieve all documents and perform the filtering in code.
TIS21-4006
TIS21-4026
=> fix: filter ObjectIds for migration post-query

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/forms/migration/ConvertObjectIdsToUuidStrings.java, src/test/java/uk/nhs/hee/tis/trainee/forms/migration/ConvertObjectIdsToUuidStringsTest.java
The migrator was based on using AbstractForm type to update the form ID, however the follow up changes to make the ID field use UUID will be a breaking change to this migrator.
Refactor the migrator to use generic Documents instead, this will avoid having to fix the implementation later. The test's will still fail to compile and will need further modification during the next steps.
TIS21-4006
TIS21-4026
=> refactor: make UUID migrator use generic document

src/main/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartAValidator.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartBValidator.java, src/main/java/uk/nhs/hee/tis/trainee/forms/migration/ConvertUuidStringsToUuidObjects.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/AbstractForm.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/AbstractFormMongoEventListener.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/AbstractCloudRepository.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartAValidatorTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartBValidatorTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/migration/ConvertObjectIdsToUuidStringsTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/migration/ConvertUuidStringsToUuidObjectsTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/model/AbstractFormMongoEventListenerTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/repository/S3FormRPartARepositoryImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/repository/S3FormRPartBRepositoryImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAServiceImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBServiceImplTest.java, src/test/resources/forms/testFormRPartA.json, src/test/resources/forms/testFormRPartB.json
Migrate the AbstractForm's `id` field from String to UUID based. Create a Mongock migration to find all String based IDs and perform the conversion to UUIDs in the database.
Modify the entity to use UUID and update the required classes and tests.
TIS21-4006
TIS21-4027
=> feat: migrate AbstractForm from string to UUID

.aws/task-definition-template.json, build.gradle, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/DeleteEventDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/enumeration/DeleteType.java, src/main/java/uk/nhs/hee/tis/trainee/forms/event/FormDeleteEventListener.java, src/main/java/uk/nhs/hee/tis/trainee/forms/migration/AddPartialDeleteMetadataToS3.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/AbstractCloudRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAService.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBService.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/impl/FormRPartAServiceImpl.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/impl/FormRPartBServiceImpl.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/forms/event/FormDeleteEventListenerTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/migration/AddPartialDeleteMetadataToS3Test.java, src/test/java/uk/nhs/hee/tis/trainee/forms/repository/S3FormRPartARepositoryImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/repository/S3FormRPartBRepositoryImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAServiceImplTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBServiceImplTest.java
- listen to the delete event queue to handle partial delete in DB
- add `deleteType` and `fixedFields` in S3 Metadata when new forms are saved
- Mongock migration to bulk add `deleteType` and `fixedFields` to Metadata of all the existing forms
TIS21-4009
TIS21-4019
TIS21-4077
TIS21-4023
=> feat: partial delete form

src/main/java/uk/nhs/hee/tis/trainee/forms/api/util/AuthTokenUtil.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/util/AuthTokenUtilTest.java
The JWT is encoded using a URL variant of Base64, which replaces `/` with `_` to avoid using reserved URL characters. AuthTokenUtil is using the standard decoder, which throws an exception when an underscore is encountered.
TIS21-4414
=> fix: incorrect decoder used for JWT token

build.gradle, src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartAResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartBResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAService.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartAResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartBResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAServiceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBServiceTest.java
In order to support the discarding of a draft form, the user must be allowed to delete any draft forms that they have created. Create a new DELETE endpoint with supporting service methods for both Part-A and Part-B forms.
TIS21-4922
TIS21-4877
=> feat: allow deletion of draft forms

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/service/FormRelocateService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRelocateServiceTest.java
to avoid unwanted form deletion in S3 during rollback due to form not found
=> fix: don't move form when the form is already attached to the target trainee

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartAValidator.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartBValidator.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartAValidatorTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/validation/FormRPartBValidatorTest.java
The validation errors are included in the response to the front-end, but since we are not doing anything with them there, and for ease of resolving any issues, it makes sense to log them here. An example log entry:
```
2024-01-24 09:50:09.834 ERROR 34216 --- [nio-8207-exec-3] u.n.h.t.t.f.a.v.FormRPartAValidator      : Validation failed: org.springframework.validation.BeanPropertyBindingResult: 3 errors
Field error in object 'FormRPartADto' on field 'validateFormRPartA.formRPartADto.cctSpecialty1': rejected value [FormRPartADto(id=071d95bd-01c2-4da1-9fb9-5cfbc524f467, traineeTisId=47165, forename=afgasflhsashfaspolhfoashf;lasfklashfklhasfasfasfasfasfasfasfasfasfasfasfasfasfasfasfkljhaslhflashfkklhfslkhasflkhasfklhasfklhasfklh, surname=null, gmcNumber=8999999, localOfficeName=Health …
```
=> fix: add backend logging for validation errors

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/WorkDto.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormFieldValidationServicePartBTest.java
Validation on the FE for this field uses StringValidationSchemaOptional (its the only field that uses this). Empty strings should be accepted.
NO-TICKET
=> fix: allow empty SiteKnownAs

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAService.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartAServiceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/FormRPartBServiceTest.java
Changes made to unsubmitted forms are not stored back to S3 until re-submitted. When getting form contents the S3 contents are the default if it exists.
This leads to changes saved to the database being ignored when returning to edit the form further. Appearing, from a user point of view, that the updates were never saved.
Update the form services to check the modification time and always return the latest version of the form.
TIS21-6130
=> fix: always get latest form contents

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartADto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartBDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/FormRPartSimpleDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/FormRPartA.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/FormRPartB.java, src/test/resources/forms/testFormRPartA.json, src/test/resources/forms/testFormRPartB.json
Update Form R Part A and Part B to allow a programme membership ID to be stored against the form, this will show which PM the form is being submitted for. Also include a new `isArcp` flag so the user can specify whether their submission is towards ARCP or not.
TIS21-5611
TIS21-6280
=> feat(formr): add linked PM and isARCP flag

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/FormRPartARepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/FormRPartBRepository.java
The `programmeMembershipId` field is not included when looking up the simple DTOs for form lists.
Add `programmeMembershipId` to the list of query fields.
TIS21-5611
=> fix(formr): include PM ID in forms list

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/service/PdfPublisherService.java, src/main/resources/application.yml, src/main/resources/templates/conditions-of-joining/gg10.html, src/main/resources/templates/conditions-of-joining/gg9.html, src/test/java/uk/nhs/hee/tis/trainee/forms/service/PdfPublisherServiceTest.java
The timestamp is incorrect for several reasons
1. The default timezone is used, which is UTC when deployed, but should use London time instead.
2. The timestamp can be out by 12 hours when the time is between 12:01 and 23:59
Add a timezone property to the application.properties, this should be defaulted to Europe/London and passed to the template engine.
Update the COJ templates to use `HH:mm` instead of `hh:mm` for the time format, eliminating the 12 hour error due to 12-hour vs 24-hour clock formatting. The timezone should also be included so the timestamp is always using London time.
TIS21-6106
TIS21-6121
=> fix: incorrect timestamp

build.gradle.kts, src/main/resources/application-local.yml
Create an `application-local.yml` file with sensible defaults for running this service locally.
The profile should be activated by setting
`SPRING_PROFILES_ACTIVE=local` in the env vars when running this service. No other env vars need to be set if everything is running directly on localhost, but `DB_HOST` and `LOCALSTACK_HOST` should still be set when running inside a container.
`SIGNATURE_SECRET_KEY` can still be used to ensure services all match, but a default value is provided.
There is still a pre-requisite that the queues and buckets listed in `application-local.yml` are created in the localstack instance.
NO-TICKET
=> chore: local application property defaults

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/DockerImageNames.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceIntegrationTest.java, src/integrationTest/resources/application-test.yml, src/main/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
Add an endpoint `/api/admin/ltft/count` which will return a count of LTFT applications that are associated with an admin's local office. The result should be filterable on status, but passing a URL parameter such `status=UNSUBMITTED,SUBMITTED`.
Local office filtering will follow, only status filtering will be supported at this point.
Refactor the Gradle build script to create an integration test suite separate from the existing test suite. This integration suite will make full use of test containers to allow testing of several layers, from API, through service, to repository.
Existing integration tests have not been moved yet.
TIS21-6599
TIS21-6938
=> feat: add LTFT count endpoint for admins

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/LtftSummaryDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/AbstractAuditedForm.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/AbstractForm.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/AbstractFormR.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/FormRPartA.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/FormRPartB.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/AbstractCloudRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/LtftFormRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/model/AbstractFormMongoEventListenerTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
Refactor the AbstractForm, Form Rs and LtftForm in to a shared, more consistent hierarchy.
Since LTFT will have a state audit history included the structure for lifecycle state and submission date will change, so those should be moved to an abstract class shared by just the existing forms (FormR Part A and B). Additionally the lastModified field will be an Instant instead of LocalDateTime, so that field should also be moved so it is only used by FormRs in its current form.
The LTFT form has been refactored to follow the conventions set by FormR, so the builder has been removed until the forms can be refactored again in sync.
NO-TICKET
=> refactor: form inheritance

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java
HACK
Without success I've tried the suggested workarounds on https://github.com/spring-projects/spring-data-rest/issues/1565  (`@JsonIgnore` or `@JsonProperty(access = JsonProperty.Access.READ_ONLY)` on the created field. Making the field final introduced other issues with inheritance, so I didn't pursue it. Using `@Version` on a new field and changing the `isNew()` code to refer to this made no difference either. 
(We don't actually use spring-data-rest specifically, but it seemed the clearest explanation of the issue from much googling around).
Heroic efforts by the author here: https://stackoverflow.com/questions/68441685/spring-data-mongodb-how-to-avoid-createdby-and-createddate-fields-update - but I'm not sure how much we want to pervert the MongoTemplate to our own base desires. …
=> fix: set created date when updating form

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/repository/FormRPartARepositoryIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/repository/FormRPartBRepositoryIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/repository/LtftRepositoryIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/LtftFormRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
Filter the result of the admin LTFT count endpoint based on the DBCs that the admin user is assigned to.
The DBCs are set as a Cognito group and added to the auth token as `cognito:groups`.
This may include non-DBC groups at some point, but those should never match a PM's DBC anyway.
TIS21-6599
TIS21-6938
=> feat: filter admin LTFT count by DBCs

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/LtftAdminSummaryDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/PersonDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/mapper/LtftMapper.java, src/main/java/uk/nhs/hee/tis/trainee/forms/mapper/TemporalMapper.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/content/LtftContent.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/LtftFormRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/mapper/TemporalMapperTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
Add an endpoint for getting Admin-facing summarries of LTFT application for the user's assigned local offices.
By default the response will include all LTFT applications for the local office ordered by the creation timestamp. But paging, sorting and status filtering are available using query parameters.
Several of the summary fields will return dummy values temporarily
- `submissionDate` will use the creation timestamp
- `reason` = `TODO`
- `daysToStart` = `40`
- `shortNotice` = `false`
- `tpd.emailStatus` = `TODO`
TIS21-6600
TIS21-6940
=> feat(ltft): admin summary endpoint

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/mapper/LtftMapper.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/LtftFormRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
Add an endpoint for admins to get LTFT application details for a given
ID.
The LTFT must be associated with one of the admin's assigned DBCs, only
non-DRAFT forms are accessible to admins.
TIS21-6602
TIS21-7011
---
The admin summary list should not include any DRAFT forms, update
LtftService to exclude DRAFTs when no filters are provided and to
remove DRAFT from the requested states if included in the request.
TIS21-6600
TIS21-7019
---
Admins do not have visibility of DRAFT LTFT forms, remove them from the
count so there is no possibility of getting a conflicting result.
TIS21-6599
TIS21-6938
=> feat(ltft): add admin detail endpoint

build.gradle.kts, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/LtftFormDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/PersonalDetailsDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/mapper/LtftMapper.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/content/CctChange.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/content/LtftContent.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
Several LTFT fields can have valid `null` values when working with a DRAFT form, if that section has not been filled in. Currently several fields are using primitive boolean and numerical types, which are being defaulted to `false`/`0`.
Update the LTFT entity and model to use non-primative types which can be defaulted to `null`.
Several of these fields should never be `null`, such as PM WTE which is always expected to be populated. However, defaulting to erroneous values causes more issues than missing data, as the source of the value becomes unknown/lost.
---
The current DTO includes CCT Date in the programme membership, but the
database model does not. The result is that the CCT Date is dropped and
cannot be retrieved again.
Add `cctDate` to the `CctChange` model and configure the …
=> fix(ltft): allow nullable fields and don't null CCT Date

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/RestResponseEntityExceptionHandler.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/identity/TraineeIdentity.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/identity/UserIdentity.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/LtftFormRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/RestResponseEntityExceptionHandlerTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
Extract the status update code that can be shared between statuses to
LtftService.updateStatus().
TIS21-6716
TIS21-7061
TIS21-7016
---
Create an admin approval endpoint
`/api/forms/admin/ltft/{formId}/approve`.
TIS21-6716
TIS21-7061
TIS21-7016
=> feat(ltft): admin approval endpoint

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/repository/LtftRepositoryIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/LtftAdminSummaryDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/LtftFormDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/mapper/LtftMapper.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/AbstractAuditedForm.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/content/LtftContent.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/LtftFormRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/mapper/LtftMapperTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/model/AbstractAuditedFormTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
The sorting and filtering of admin endpoints is currently limited as the internal field names are required.
As the internal field names are not transparent to the client, it should be possible to sort and filter based on the DTO field names.
Update LtftService to translate the supported field names for both sorting and filtering. The user filters should be added on top of the filters for DBC and non-DRAFT LTFTs, but not replace them.
To enable sorting on `submissionDate`, which is a calculated field, it should be made in to an actual field on the database model. The `submitted` timestamp will be updated each time the LTFT is submitted. Refactor AbstractAuditedForm to add the new field and remove the existing `getSubmitted()` method.
Update `LtftAdminSummaryDto` to include the missing …
=> feat(ltft): sorting and filtering admin endpoints

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/PdfService.java, src/main/resources/static/css/override.css, src/main/resources/templates/ltft/admin.html, src/test/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/PdfServiceTest.java
Add an endpoint to allow TIS admins to download LTFT details as a PDF. The API path is the same as getting the JSON detail, but the `Accept` header should be set to `application/pdf`.
The PDF template is rough but data-wise complete. Further restructuring of the HTML and CSS styling will be needed.
TIS21-6635
TIS21-7177
=> feat(ltft): admin details PDF

src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/LtftResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/LtftFormDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/views/ReadOnly.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/views/Trainee.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
Several properties on the LTFT DTO should be read-only
- `formRef`
- `revision`
- `assignedAdmin`
- `status`
- `created`
- `lastModified`
Currently it is possible to create new LTFTs with user-provided values in these fields. Any given values should be rejected/ignored and server-generated values should be persisted and returned in the response instead.
Update LtftFormDto to add validation to ensure that the values for these properties is `null` during LTFT creation.
A `ReadOnly` JsonView should be used to make sure the deserialized DTO never contains values for these fields. This will cause the validation to always pass, but the dual-front approach ensures less chance of misconfiguration allowing values through.
TIS21-7137
TIS21-7149
=> feat(ltft): restrict readonly properties on create

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/LtftResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/LtftFormDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/validation/Update.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/content/LtftContent.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
fix(ltft): restrict edits to DRAFT and UNSUBMITTED
Currently the API allows edits to forms in any state, this should be
restricted to only those in DRAFT or SUBMITTED states.
TIS21-7137
TIS21-7150
---
fix(ltft): ignore read-only fields on update
When a trainee updates an LTFT it is possible to provide values for the
following fields, which should be read only:
- `formRef`
- `revision`
- `assignedAdmin`
- `status`
- `created`
- `lastModified`
Update LtftFormDto and LtftResource to ensure that the above fields are
either validated or excluded from deserialization using JsonViews.
Update LtftService to update the existing form content instead of
persisting the user-provided data. The provided content will be
extracted and inserted in to the existing form, with the exception of …
=> fix(ltft): restrict trainee ability to modify forms

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/repository/LtftSubmissionHistoryRepositoryIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/service/LtftSubmissionHistoryServiceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/mapper/LtftMapper.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/LtftSubmissionHistory.java, src/main/java/uk/nhs/hee/tis/trainee/forms/repository/LtftSubmissionHistoryRepository.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftSubmissionHistoryService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/model/LtftSubmissionHistoryTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftSubmissionHistoryServiceTest.java
There is a rather expansive collection of indexes for the new collection, but it didn't feel worth refactoring the AbstractAuditedForm inheritance given we may in future need search functionality that depends on those indexes.
TIS21-7097
=> feat: snapshot submitted LTFT forms

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/repository/LtftRepositoryIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/repository/LtftSubmissionHistoryRepositoryIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/content/LtftContent.java
Service is currently failing to deploy with error
```
Failed to instantiate [org.springframework.data.mongodb.core.MongoTemplate]: Factory method 'mongoTemplate' threw exception with message: Cannot create index for 'content.programmeMembership.designatedBodyCode' in collection 'LtftSubmissionHistory' with keys 'Document{{content.programmeMembership.designatedBodyCode=1}}' and options 'Document{{name=content.programmeMembership.designatedBodyCode}}' 
...
Caused by: com.mongodb.MongoCommandException: Command failed with error 67: 'namespace name generated from index name is too long'
```
This fix assumes we are ok with manually deleting the existing index on this field in the LtftForm collection, since the name will change. Otherwise I'll cook-up a mongock.
NO-TICKET
=> fix: index name length

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/dto/LtftFormDto.java, src/main/java/uk/nhs/hee/tis/trainee/forms/mapper/LtftMapper.java, src/main/java/uk/nhs/hee/tis/trainee/forms/model/AbstractAuditedForm.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/test/java/uk/nhs/hee/tis/trainee/forms/model/AbstractAuditedFormTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
Refactor the AbstractAuditedForm to move the assignedAdmin property in to the StatusInfo. This allows it to be record both against the current status and in the history.
When updating the state of a form the previous assigned admin should be carried forward, similarly when assigning an admin the previous state should be carried forward.
TIS21-7082
TIS21-7086
=> feat(ltft): capture history of assigned admins

.aws/task-definition-template.json, build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/LtftService.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/tis/trainee/forms/service/LtftServiceTest.java
When a new admin is assigned to an LTFT the history is updated and the
LTFT should be published via SNS for other services to react to.
Specifically the NDW export should trigger to update the assignment
details in NDW reports.
TIS21-7082
TIS21-7086
---
When an admin is assigned multiple times it causes an audit history
entry each time, even though nothing has changed.
Update AbstractAuditedForm to check if the new assignment matches the
existing assignment and skip the update if it does.
The whole Person object should be checked to account for any of name,
email or role changing and needing to be updated. But if all entries
match then no status/history update should be done.
This check is already covered for status history due to restricted
transitions stopping the same state from being …
=> feat(ltft): publish LTFT on assignment update

.github/workflows/ci-cd.yml, .github/workflows/pr-analysis.yml, build.gradle.kts, settings.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceIntegrationTest.java
Use the trainee version catalog to determine plugin and dependency versions.
Update the GitHub Actions workflows to enabled build scan publishing.
NO-TICKET
=> build: migrate to version catalog

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/AdminLtftResourceIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceIntegrationTest.java, src/main/java/uk/nhs/hee/tis/trainee/forms/service/exception/ExceptionTranslator.java
The integration tests for LTFT validation started failing due to changes on the build server. While the exact reason for the changed behaviour is unknown, it has highlighted a conflict between
`RestResponeEntityExceptionHandler` and `ExceptionTranslator`.
Update the `ExceptionTranslator` to specify which rest controllers it should be responsible for. The LTFT controllers will continue to use the Problem Detail response with `application/problem+json` content type.
NO-TICKET
=> fix: LTFT exception handling

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/TestJwtUtil.java, src/main/java/uk/nhs/hee/tis/trainee/forms/interceptor/AdminIdentityInterceptor.java, src/test/java/uk/nhs/hee/tis/trainee/forms/interceptor/AdminIdentityInterceptorTest.java
Based on cognito role. Same approach as used in tis-trainee-details cct endpoints, fwiw.
TIS21-7304
=> feat: limit admin/ltft endpoints

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/tis/trainee/forms/api/LtftResourceIntegrationTest.java, src/main/resources/templates/ltft/trainee.html
- Hide form status details for DRAFT
Hide status details section for DRAFT LTFT (including form name, created date, modified date and reference fields) to match the behaviour of the FE LTFT view page)
- Check empty string for field values
Current the fields show "Not provided" when null and blank for empty string. Use `#strings.isEmpty()`, so it will show "Not provided" for both null and empty string to match with the FE.
=> fix: update LTFT PDF

src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartAResource.java, src/main/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartBResource.java, src/main/resources/application-local.yml, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartAResourceTest.java, src/test/java/uk/nhs/hee/tis/trainee/forms/api/FormRPartBResourceTest.java
This enables PDFs for submitted FormRs to be published, in the same way that CoJ PDF's are published.
They will be picked up by SNS (tis-trainee-[env]-pdf-generated.fifo), and a new subscription has been added (tis-trainee-notifications-[env]-formr-pdf-generated.fifo), filtered to only pick up formR form_types. 
A new listener will be added to the notifications service to generate the emails and attach the PDFs, and the existing listener for general saved form Rs that generates the generic email notification will be adjusted to ignore those that are SUBMITTED, to avoid duplication of emails for submitted formRs, but to allow any other form states to still generate these generic emails if the 'alwaysStoreFiles' config is ever set to true in future (cf. …
=> Feat: formR PDF when submitted
